import Head from "next/head";

import { Wrapper } from "@/components/Wrapper";
import { MainBanner } from "@/components/MainBanner";
import { ProductCard } from "@/components/product/ProductCard";
import { FixedCartIcon } from "@/components/FixedCartIcon";
import { ProductCarousel } from "@/components/sections/ProductCarousel";
import { LocationSection } from "@/components/sections/LocationSection";
import { AdvantagesSection } from "@/components/sections/AdvantagesSection";

import { fetchDataFromApi } from "@/utils/api";

type HomeProps = {
  discountedProducts: Product[];
  bannerList: Banner[];
};

export const getStaticProps = async () => {
  const discountedProducts = await fetchDataFromApi(
    "/api/products?populate=deep&filters[isDiscounted]=true"
  );
  const bannerList = await fetchDataFromApi("/api/banners?populate=*");

  return {
    props: {
      discountedProducts: discountedProducts.data,
      bannerList: bannerList.data,
    },
  };
};

export default function Home({ discountedProducts, bannerList }: HomeProps) {
  return (
    <>
      <Head>
        <title>Akula</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/A.png" />
      </Head>

      <Wrapper>
        <MainBanner bannerList={bannerList} />

        {discountedProducts.length && (
          <ProductCarousel title="Товары со скидкой" url="/category/sale">
            {discountedProducts
              .reverse()
              .slice(0, 8)
              .map(({ id, attributes }) => (
                <ProductCard
                  key={id}
                  imageUrl={attributes.images?.data[0].attributes.url}
                  slug={attributes.slug}
                  price={attributes.price}
                  name={attributes.name}
                />
              ))}
          </ProductCarousel>
        )}

        <AdvantagesSection />

        <LocationSection isTitleOn={true} isMarginTop={true} />

        <FixedCartIcon />
      </Wrapper>
    </>
  );
}
